export const businesses = [
  {
    id: "1scrcmp",
    name: "Mission Plaza",
    capacity: 3000,
    photo: "/images/SantaCruz/missionPlaza.jpeg",
    startTime: [8, 0],
    endTime: [22, 0],
    price: 547,
    city: "Santa Cruz",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "2scrcdpp",
    name: "Depot Park Plaza",
    capacity: 1000,
    photo: "/images/SantaCruz/depotParkPlaza.jpeg",
    startTime: [8, 0],
    endTime: [22, 0],
    price: 150,
    city: "Santa Cruz",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "3scrccb",
    name: "Cowell Beach",
    capacity: 400,
    photo: "/images/SantaCruz/cowellBeach.jpg",
    startTime: [6, 0],
    endTime: [22, 0],
    price: 480,
    city: "Santa Cruz",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "4scrcmb",
    name: "Main Beach",
    capacity: 6000,
    photo: "/images/SantaCruz/mainBeach.jpg",
    startTime: [10, 0],
    endTime: [22, 0],
    price: 3497,
    city: "Santa Cruz",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "1sclccpp",
    name: "Central Park Pavillian",
    capacity: 3000,
    photo: "/images/SantaClara/CentralParkPavilian.png",
    startTime: [8, 0],
    endTime: [22, 0],
    price: 547,
    city: "Santa Clara",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "2sclcps",
    name: "Poplar Street",
    capacity: 5000,
    photo: "/images/SantaClara/PoplarStreet.png",
    startTime: [0, 0],
    endTime: [24, 0],
    price: 10,
    city: "Santa Clara",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "3sclcaa",
    name: "Arbor Area",
    capacity: 250,
    photo: "/images/SantaClara/ArborArea.png",
    startTime: [6, 0],
    endTime: [22, 0],
    price: 256,
    city: "Santa Clara",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "4sclcccp",
    name: "Civic Center Park",
    capacity: 500,
    photo: "/images/SantaClara/CivicCenterPark.png",
    startTime: [6, 0],
    endTime: [22, 0],
    price: 370,
    city: "Santa Clara",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "1berksp",
    name: "Skate Park",
    capacity: 500,
    photo: "/images/Berkeley/SkatePark.png",
    startTime: [8, 0],
    endTime: [21, 0],
    price: 275,
    city: "Berkeley",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "2berklop",
    name: "Live Oak Park",
    capacity: 5,
    photo: "/images/Berkeley/LiveOakPark.png",
    startTime: [6, 0],
    endTime: [22, 0],
    price: 369,
    city: "Berkeley",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "3berkcp",
    name: "Codornices park",
    capacity: 500,
    photo: "/images/Berkeley/CodornicesPark.png",
    startTime: [5, 0],
    endTime: [23, 0],
    price: 300,
    city: "Berkeley",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "4berkscp",
    name: "Strawberry Creek Park",
    capacity: 500,
    photo: "/images/Berkeley/StrawberryCreekPark.png",
    startTime: [8, 0],
    endTime: [21, 0],
    price: 375,
    city: "Berkeley",
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "5berksc",
    name: "Southern Creations",
    type: "Food",
    subtype: "Food Booth",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/southernCreations.jpeg",
    description: "We are a BBQ and Southern Style Food Service company.",
    price: 5300,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "6berkssfcc",
    name: "Suis Suis French Caribbean Cuisine",
    type: "Food",
    subtype: "Food Booth",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/suisSuisFrenchCaribbeanCuisine.png",
    description:
      "Suis Suis Caribbean Cuisine is an Afro-Caribbean Culinary Fusion which brings the uniquely cultivated recipes and flavors from across the Caribbean and African Diaspora to your table in minutes.",
    price: 2000,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "7berkst",
    name: "Sparkle Tatts",
    type: "Cosmetics",
    subtype: "Cosmetics",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/sparkleTatts.jpeg",
    description:
      "Pro hand-crafted/CUSTOMIZED glitter & Crystal Body Tattoos. Festive & fun!!! Consider all the occasions that would be more FESTIVE!....Birthday, school fund raisers, anniversary, graduation, music festival, fairs and much more. I can create custom designs! I provide affordable safe, non-toxic (glueless!) sparkle tattoos & gems, Face, Cheek art, Sparkle! Fun, unique and contemporary way to express yourself. Appeals to all! We offer a great selection to choose, children are excited to get SparkleTatts with their favorite Superheroes. I also create paper signs, banners, & grocery style paper. Insured A+",
    price: 300,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "8berkcbf",
    name: "Clothes by Fraud",
    type: "Clothing",
    subtype: "Clothing",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/clothesByFraud.jpeg",
    description:
      "Selling fraudulent designer items. They look exactly like the originals. Don’t report me to the police!",
    price: 50,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "9berkwce",
    name: "Winners Circle Entertainment",
    type: "Clothing",
    subtype: "Clothing",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/winnersCircleEntertainment.jpeg",
    description:
      "Winner's Circle Tours and events was put together by Supa Soop (Derrell Alexander) and a community of independent artists, sponsored by Winner's Circle Clothing Co US & Canada",
    price: 50,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "10berkbadc",
    name: "Bay Area Djs CA",
    type: "Entertainment",
    subtype: "DJ",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/bayAreaDjsCa.jpeg",
    description:
      "We provide the right music for your timeless moments.Bay Area Djs CA. is a mobile Dj company. We provide music for all types of events and occasions. Since the mid 1990s, we have hosted a variety of events in and out of the Bay area, as far as Denver, Colorado. System comes equipped with MC services, lights, and fog machine. Our Djs are fluent in English and Spanish, which means we are able to make translations at any reception if necessary. Our Djs are professional and respectful at all events and always arrive one hour before start time of the reception. If needed, our references are available upon request. We have different packages available to fit your event.",
    price: 875,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "11berkcamml",
    name: "Club Anywhere! - Mobile Music & Lighting",
    type: "Entertainment",
    subtype: "DJ",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/clubAnywhereMobileMusicAndLighting.jpeg",
    description:
      "We've got your shelter in place outdoor entertainment ready when you are! We love music and having a great time! During these unstable times we decided to design a completely mobile party. We bring high quality professional audio equipment, professional lighting (for nighttime gigs) and thousands of smoke filled bubbles! We will mix your favorite music in advance and pull up to your car parade, your facility, driveway, parking lot or even a park. Our service is only outdoors and where all guests wear masks and follow the existing social distance requirements. Our special promotion is $99 for 45 minutes with 15 miles from Castro Valley included. Additional travel fee beyond 15 miles.",
    price: 250,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "12berkk",
    name: "Knowledge",
    type: "Entertainment",
    subtype: "Live Music",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/knowledge.jpeg",
    description:
      "durt gang we a rap group out of pittsburg ca we do live perfomances we give off a Postive vide we have good engery. We love entertaining our audience and also like networking.",
    price: 100,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "13berkr",
    name: "Razteria",
    type: "Entertainment",
    subtype: "Solo Artist",
    location: "Berkeley",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/Berkeley/razteria.jpeg",
    description:
      "San Francisco, CA, based artist Razteria (aka Renée Asteria) can be described as a fusion of No Doubt and Bomba Estéreo. Her multicultural roots (Bolivia/Netherlands) are reflected in her music, as she crosses musical genres with powerful messages in multiple languages. Over the past decade, Razteria has planted musical seeds throughout the Americas and Europe. Noteworthy performances include Reggae on the River, World One Festival, World Fest Los Angeles, Northwest World Reggae Festival and the Montreal Jazz festival, to name a few.",
    price: 500,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "1scrfmmme",
    name: "Mangos Mexican Móvil Express",
    type: "Food",
    subtype: "Food Trucks",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/mangosMexicanMovilExpress.jpeg",
    description: `				
Mangos Móvil Express and their accompanying food trailer Mango Mexican Grill strive to honor some of the first Mexican restaurants to grace San Jose, CA back in the ‘90s. The goal isn’t just providing great food, although they do so in spades. The folks here look to bring a relaxed, welcoming atmosphere to patrons, making it the perfect pit-stop for quality eats combined with a chill vibe sure to lift your mood.
`,
    price: 1300,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "2scresm",
    name: "Sang Matiz",
    type: "Entertainment",
    subtype: "Live Music",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/sangMatiz.jpg",
    description: `					
Energetic, Unique, Hot Latin/World Sounds! Sang Matiz Band plays a diverse repertoire of Afro-Brazilian/Peruvian rhythms with Flamenco finger picking and touches of Funk/R&B/Pop. This eclectic band also infuses tropical rhythms such as Cumbias, Salsa, Son Cubano, Merengue and more contemporary styles like Rock ballads, Latin Reggae, and SKA.The extended repertoire of styles and rhythms, gives the band a special mark making them exclusive for your event or venue.`,
    price: 600,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "3screiath",
    name: "Isaac and The Haze",
    type: "Entertainment",
    subtype: "Live Music",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/isaacAndTheHaze.png",
    description: `					
Isaac and The Haze are your go-to party band in the Santa Cruz and Bay Area regions! Isaac and The Haze have come together with one goal: to get you moving all night to our live versions of your favorite club anthems, dance floor burners, and pop hits. Add in the best classic tracks, and you’ve got a recipe for amazing memories for you and your friends, customers, and guests!
`,
    price: 800,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "4screemf",
    name: "Elise MacGregor Ferrell",
    type: "Entertainment",
    subtype: "Solo Artist",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/eliseMacGregorFerrel.jpg",
    description: `				
Scottish Bagpipes can reach deep into your soul when the instrument is tuned perfectly and the performer has clean fingering and good rhythm. Anything less can cause this finicky instrument to issue a terrible noise. So if you are seeking music for a wedding, funeral, or other special ceremony, please listen carefully to each player's demos, consider where each of your bidders live, and if you get unequal price quotes, please ask yourself what might account for the differences. Generally people hire me for putting soulful expression into slow music, giving fun variety concerts, and knowing lots of peppy Irish and Scots-Canadian songs. I also lead one of the Bay Area's busiest Celtic bands.
`,
    price: 600,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "5screke",
    name: "Katie Ekin",
    type: "Entertainment",
    subtype: "Solo Artist",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/katieEkin.jpg",
    description: `					
Katie is an award winning singer-songwriter with 9 years of performing experience. For the past few years she has been continuously playing gigs, weddings, and events up and down the west coast. She has two self released EP's available on iTunes and Spotify, 10 songwriting and performing awards- including a top 40 place in the Grammy Gig of A Lifetime Contest, and has been featured in numerous national radio shows and articles for her music. Katie is available to perform as an acoustic act and has personal and portable PA equipment to provide for both in/outdoor events. As well as 300+ original songs under her belt, she also a large repertoire of past and current cover songs.
`,
    price: 700,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "6screds",
    name: "DJ Swift",
    type: "Entertainment",
    subtype: "DJ",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/djSwift.jpeg",
    description: `					
I provide a continuous stream of get up off your butt music and move! aka I'm a DJ. `,
    price: 300,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "7screoa",
    name: "OÄf!",
    type: "Entertainment",
    subtype: "DJ",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/OAf!.png",
    description: `					
DJ OÄF! will mix all your favorite music at your party. Whether it's new Top 40, classic rock, hip hop, country, 80's, disco, classical, or jazz, DJ OÄF! has got what you need. Send in unlimited song requests or just request the genres you want to dance to! `,
    price: 600,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "8scrclothescbf",
    name: "Clothes by Fraud",
    type: "Clothing",
    subtype: "Brand Items",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/clothesByFraud.jpeg",
    description: `					
Selling fraudulent designer items. They look exactly like the originals. Don’t report me to the police!`,
    price: 50,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "9scrcosmexx",
    name: "Exxotic Effects Artistry",
    type: "Cosmetics",
    subtype: "Makeup Artist",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaCruz/exxoticEffectsArtistry.jpg",
    description: `					
Traveling Makeup Artist within the Bay Area for all occasions. `,
    price: 1000,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "1sclfcnba",
    name: "Chick 'N' Bros",
    type: "Food",
    subtype: "Food Trucks",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/ChickNBrosTruck.png",
    description: `					
    Chick N' Bros is a Nashville Hot Chicken Sandwich food truck located in the heart of the Bay Area. Chick N' Bros offers a variety of chicken sandwich flavors that you can choose from! `,
    price: 75,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "2sclfrict",
    name: "Rockos Ice Cream Tacos",
    type: "Food",
    subtype: "Food Trucks",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/RockosIceCreamTruck.png",
    description: `					
     Rocko's was founded in 2013 to serve carefully crafted and custom-made ice cream tacos using high quality, locally sourced, and organic ingredients; all wrapped up in one cute, little package. `,
    price: 95,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "3sclfht",
    name: "Hula Truck",
    type: "Food",
    subtype: "Food Trucks",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/HulaTruck.png",
    description: `					
    Pacific Island Flavor with a NorCal Twist.`,
    price: 98,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "4sclfbt",
    name: "Berlin Eatz",
    type: "Food",
    subtype: "Food Trucks",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/BerlinTruck.png",
    description: `					
    My name is Uli and I am originally from a small town near Cologne in Germany. I have always missed the hearty traditional German dishes I grew up eating. After having worked in the relocation industry for the past 12 years, I learned that I was not alone with my cravings for German street food, so the idea of ‘Berlin Eatz’ was born! We offer authentic recipes passed through my family for generations. Guten Appetit!  `,
    price: 100,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "5sclfct",
    name: "Charlotte Truffles",
    type: "Food",
    subtype: "Food Booths",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/CharlotteTruffles.png",
    description: `					
    We choose flavors that represent a specific culture. And we look forward to represent more cultures as we expand our product offer. Ultimately, I am celebrating the diversity of our community through chocolates. `,
    price: 90,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "6sclfcb",
    name: "Cramers Bagels",
    type: "Food",
    subtype: "Food Booths",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/CramersBagels.png",
    description: `					
    We’re the place for great bagels at a Great place! We have a variety to choose from! `,
    price: 85,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },

  {
    id: "7sclcoshc",
    name: "Henna Creationz",
    type: "Cosmetics",
    subtype: "Henna",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/Henna.png",
    description: `	
    Henna, also known as mehndi, is the ancient art of dyeing the skin with paste made from powdered leaves from the henna plant. Henna Creationz is a team of Henna Artists that provides services for all kinds of events.`,
    price: 200,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "8sclcossw",
    name: "Sweeney Beauty",
    type: "Cosmetics",
    subtype: "Makeup Artist",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/Sweeney.png",
    description: `	
    I offer makeup looks for any person, to feel their best on the outside as well as inside. Social media is Jaime Sweeney
    `,
    price: 140,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "9sclclotcl",
    name: "Classic Loot",
    type: "Clothing",
    subtype: "Unique Fashion",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/ClassicLoot.png",
    description: `	
    We're a couple of hunters/gatherers/makers. We travel all around to find unique fashion pieces, whether they are thrift, new, or handmade.
    `,
    price: 478,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "10sclclothc",
    name: "Cukui",
    type: "Clothing",
    subtype: "Design",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/Cukui.png",
    description: `	
    Cukui is rooted from a melting pot of ethnic cultures, tattoo artists, and graffiti heads. We pride ourselves in creating hand drawn illustrations and producing them in limited edition designs. 
    `,
    price: 360,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "11sclcosme",
    name: "Magickal Entertainment",
    type: "Cosmetics",
    subtype: "Face Painting and More",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/MagickalEntertainment.png",
    description: `	
    For kids, teens and adults! We offer balloon twisting, face painting, temporary tattoos, glitter tattoos, henna, character/walk-around, and pirate party services. We have over 30 years of entertainment experience, and we love making people smile!
    `,
    price: 555,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "12sclef1",
    name: "Far 1",
    type: "Entertainment",
    subtype: "Solo Artist or Band",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/Far1Band.png",
    description: `	
    Spiritual and uplifting music great to bring joy to a celebration. Original songs which touch on various music styles, Reggae, African Highlife, R&B and Spiritual. The goal of the music is to bring harmony and love to the listeners. I can perform as a solo artist - acoustic or to tracks, as a three piece acoustic or as a 5 piece band with Drums, Bass, 2 Guitars and Percussions. Great music to celebrate life and enjoy divine connections with friends, family, and community.
    `,
    price: 2000,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "13scletmm",
    name: "Trio Mariachi Mexico",
    type: "Entertainment",
    subtype: "Band",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/TrioMariachiMexico.png",
    description: `	
    We play the best of the traditional and most recent Mexican/Latin music such as Boleros, Baladas, Rancheras, Sones, Cumbias, Favorite American Standards.
    `,
    price: 998,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "14scleandte",
    name: "A New Day & Time Entertainment",
    type: "Entertainment",
    subtype: "DJ",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/ANewDayAndTimeEntertainment.png",
    description: `	
    A New Day And Time Entertainment is here to provide quality music and services for your special occasions.Our music collection has a wide variety which includes hip hop, R&B, old school funk, disco, latin, classic rock, 80s new wave, reggae/dancehall, blues and jazz. We love taking special requests and creating long lasting memories! Let us take your event to the next level!				
    `,
    price: 1000,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "15scledjs",
    name: "Dj Shy",
    type: "Entertainment",
    subtype: "DJ",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "/images/SantaClara/DjShy.png",
    description: `					
    Hey there! I go by Dj Shy, but my name is Tia.The amount of music genres I play is a handful. I can mix your old classic jams but can easily switch it up into some Hip-Hop, or, Dancehall, or House.
    `,
    price: 500,
    daysOpen: {
      Sun: true,
      Mon: true,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
];
