export const businesses = [
  {
    id: "1a",
    name: "Jazzy Beats",
    type: "Entertainment",
    subtype: "Live Music",
    location: "Sacramento",
    startTime: [8, 0],
    endTime: [20, 0],
    photo: "",
    description: "",
    price: 450.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "2a",
    name: "Julie + Ghosts",
    type: "Entertainment",
    subtype: "DJ",
    location: "Santa Cruz",
    startTime: [5, 0],
    endTime: [10, 0],
    photo: "",
    description: "",
    price: 500.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "3a",
    name: "Loco",
    type: "Entertainment",
    subtype: "DJ",
    location: "Santa Cruz",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "",
    description: "",
    price: 200.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "4a",
    name: "Zay Beats",
    type: "Entertainment",
    subtype: "Solo Artist",
    location: "Santa Clara",
    startTime: [2, 0],
    endTime: [17, 0],
    photo: "",
    description: "",
    price: 1000.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "1b",
    name: "Zippys",
    type: "Food",
    subtype: "Restaurant",
    location: "Santa Clara",
    startTime: [0, 0],
    endTime: [24, 0],
    photo: "",
    description: "#1 Chili",
    price: 5.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "2b",
    name: "Goma Tei",
    type: "Food",
    subtype: "Restaurant",
    location: "Sacramento",
    startTime: [11, 0],
    endTime: [17, 0],
    photo: "",
    description: "#1 Tan Tan Ramen",
    price: 100.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "3b",
    name: "Bobbys Truck",
    type: "Food",
    subtype: "Foodtruck",
    location: "Santa Cruz",
    startTime: [8, 0],
    endTime: [23, 0],
    photo: "",
    description: "I sell food",
    price: 100.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "1c",
    name: "Vera's Beauty",
    type: "Cosmetics",
    subtype: "Nail",
    location: "Santa Clara",
    startTime: [10, 0],
    endTime: [18, 0],
    photo: "",
    description: "I am so good at doing nails",
    price: 500.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "2c",
    name: "Clown Studio",
    type: "Cosmetics",
    subtype: "Facepaint",
    location: "Sacramento",
    startTime: [10, 0],
    endTime: [20, 0],
    photo: "",
    description: "Look like a clown",
    price: 100.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "3c",
    name: "Mens Cuts",
    type: "Cosmetics",
    subtype: "Hair",
    location: "Santa Cruz",
    startTime: [7, 0],
    endTime: [22, 0],
    photo: "",
    description: "For men",
    price: 100.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "1d",
    name: "Payless",
    type: "Clothing",
    subtype: "Shoes",
    location: "Santa Clara",
    startTime: [7, 0],
    endTime: [18, 0],
    photo: "",
    description: "I am so good at shoes",
    price: 50.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "2d",
    name: "Tankies",
    type: "Clothing",
    subtype: "Top",
    location: "Sacramento",
    startTime: [10, 0],
    endTime: [20, 0],
    photo: "",
    description: "Tank tops for everyone",
    price: 100.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
  {
    id: "3d",
    name: "Pantaloony",
    type: "Clothing",
    subtype: "Bottom",
    location: "Santa Cruz",
    startTime: [7, 0],
    endTime: [22, 0],
    photo: "",
    description: "For people who love jeans",
    price: 100.0,
    daysOpen: {
      Sun: true,
      Mon: false,
      Tues: true,
      Wed: true,
      Thur: true,
      Fri: true,
      Sat: true,
    },
  },
];
