/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const FILE_URL =
  "https://gltfloaders.s3-us-west-1.amazonaws.com/city.gltf";

export default function ModelCity(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(FILE_URL);
  // const { nodes, materials } = useGLTF("City.gltf", true);
  return (
    <group ref={group} {...props}>
      <mesh
        material={nodes.Plane01.material}
        geometry={nodes.Plane01.geometry}
        position={[-2310.69, 0, 703.14]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <group position={[738.49, 0, 8.33]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_1_0.material} geometry={nodes.mesh_1_0.geometry} />
        <mesh material={nodes.mesh_1_1.material} geometry={nodes.mesh_1_1.geometry} />
      </group>
      <group position={[-403.97, 0, -596.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.67, 0.67, 0.19]}>
        <mesh material={nodes.mesh_2_0.material} geometry={nodes.mesh_2_0.geometry} />
        <mesh material={nodes.mesh_2_1.material} geometry={nodes.mesh_2_1.geometry} />
      </group>
      <group position={[-782.56, 0, 573.14]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.77, 0.98, 0.4]}>
        <mesh material={nodes.mesh_3_0.material} geometry={nodes.mesh_3_0.geometry} />
        <mesh material={nodes.mesh_3_1.material} geometry={nodes.mesh_3_1.geometry} />
      </group>
      <group position={[228.51, 0, 595.35]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.09, 0.98, 0.8]}>
        <mesh material={nodes.mesh_4_0.material} geometry={nodes.mesh_4_0.geometry} />
        <mesh material={nodes.mesh_4_1.material} geometry={nodes.mesh_4_1.geometry} />
      </group>
      <group position={[533, 0, -553.71]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.09, 0.98, 0.8]}>
        <mesh material={nodes.mesh_5_0.material} geometry={nodes.mesh_5_0.geometry} />
        <mesh material={nodes.mesh_5_1.material} geometry={nodes.mesh_5_1.geometry} />
      </group>
      <group position={[-241.43, 0, -610.49]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.77, 0.98, 0.4]}>
        <mesh material={nodes.mesh_6_0.material} geometry={nodes.mesh_6_0.geometry} />
        <mesh material={nodes.mesh_6_1.material} geometry={nodes.mesh_6_1.geometry} />
      </group>
      <group position={[-819.62, 0, -596.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.67, 0.67, 0.19]}>
        <mesh material={nodes.mesh_7_0.material} geometry={nodes.mesh_7_0.geometry} />
        <mesh material={nodes.mesh_7_1.material} geometry={nodes.mesh_7_1.geometry} />
      </group>
      <group position={[-1235.28, 0, -596.53]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.67, 0.67, 0.19]}>
        <mesh material={nodes.mesh_8_0.material} geometry={nodes.mesh_8_0.geometry} />
        <mesh material={nodes.mesh_8_1.material} geometry={nodes.mesh_8_1.geometry} />
      </group>
      <group position={[-1638.17, 0, 20.83]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_9_0.material} geometry={nodes.mesh_9_0.geometry} />
        <mesh material={nodes.mesh_9_1.material} geometry={nodes.mesh_9_1.geometry} />
      </group>
      <group position={[-1688.93, 0, 2313.81]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.67, 0.67, 0.19]}>
        <mesh material={nodes.mesh_10_0.material} geometry={nodes.mesh_10_0.geometry} />
        <mesh material={nodes.mesh_10_1.material} geometry={nodes.mesh_10_1.geometry} />
      </group>
      <group position={[-1833.58, 0, 886.27]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.77, 0.98, 0.4]}>
        <mesh material={nodes.mesh_11_0.material} geometry={nodes.mesh_11_0.geometry} />
        <mesh material={nodes.mesh_11_1.material} geometry={nodes.mesh_11_1.geometry} />
      </group>
      <group position={[-312.72, 0, 1406.69]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_12_0.material} geometry={nodes.mesh_12_0.geometry} />
        <mesh material={nodes.mesh_12_1.material} geometry={nodes.mesh_12_1.geometry} />
      </group>
      <group position={[-1847.46, 0, -1016.97]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_13_0.material} geometry={nodes.mesh_13_0.geometry} />
        <mesh material={nodes.mesh_13_1.material} geometry={nodes.mesh_13_1.geometry} />
      </group>
      <group position={[180.25, 0, 3507.75]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_14_0.material} geometry={nodes.mesh_14_0.geometry} />
        <mesh material={nodes.mesh_14_1.material} geometry={nodes.mesh_14_1.geometry} />
      </group>
      <group position={[-3100.8, 0, 151.56]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_15_0.material} geometry={nodes.mesh_15_0.geometry} />
        <mesh material={nodes.mesh_15_1.material} geometry={nodes.mesh_15_1.geometry} />
      </group>
      <group position={[-2970.61, 0, -1810.88]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_16_0.material} geometry={nodes.mesh_16_0.geometry} />
        <mesh material={nodes.mesh_16_1.material} geometry={nodes.mesh_16_1.geometry} />
      </group>
      <group position={[-3631.95, 0, 2637.92]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_17_0.material} geometry={nodes.mesh_17_0.geometry} />
        <mesh material={nodes.mesh_17_1.material} geometry={nodes.mesh_17_1.geometry} />
      </group>
      <group position={[-1700.57, 0, 1721]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_18_0.material} geometry={nodes.mesh_18_0.geometry} />
        <mesh material={nodes.mesh_18_1.material} geometry={nodes.mesh_18_1.geometry} />
      </group>
      <group position={[874.44, 0, 1318.13]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_19_0.material} geometry={nodes.mesh_19_0.geometry} />
        <mesh material={nodes.mesh_19_1.material} geometry={nodes.mesh_19_1.geometry} />
      </group>
      <group position={[-3086.15, 0, -708.4]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_20_0.material} geometry={nodes.mesh_20_0.geometry} />
        <mesh material={nodes.mesh_20_1.material} geometry={nodes.mesh_20_1.geometry} />
      </group>
      <group position={[-2398.36, 0, 2439.07]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_21_0.material} geometry={nodes.mesh_21_0.geometry} />
        <mesh material={nodes.mesh_21_1.material} geometry={nodes.mesh_21_1.geometry} />
      </group>
      <group position={[346.96, 0, 2777.13]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_22_0.material} geometry={nodes.mesh_22_0.geometry} />
        <mesh material={nodes.mesh_22_1.material} geometry={nodes.mesh_22_1.geometry} />
      </group>
      <group position={[-606.73, 0, 2225.43]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_23_0.material} geometry={nodes.mesh_23_0.geometry} />
        <mesh material={nodes.mesh_23_1.material} geometry={nodes.mesh_23_1.geometry} />
      </group>
      <group position={[-2474.98, 0, 1814.95]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_24_0.material} geometry={nodes.mesh_24_0.geometry} />
        <mesh material={nodes.mesh_24_1.material} geometry={nodes.mesh_24_1.geometry} />
      </group>
      <group position={[42.75, 0, 20.83]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_25_0.material} geometry={nodes.mesh_25_0.geometry} />
        <mesh material={nodes.mesh_25_1.material} geometry={nodes.mesh_25_1.geometry} />
      </group>
      <group position={[2164.28, 0, 359.35]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_26_0.material} geometry={nodes.mesh_26_0.geometry} />
        <mesh material={nodes.mesh_26_1.material} geometry={nodes.mesh_26_1.geometry} />
      </group>
      <group position={[-2563.85, 0, 1212.44]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.77, 0.98, 0.4]}>
        <mesh material={nodes.mesh_27_0.material} geometry={nodes.mesh_27_0.geometry} />
        <mesh material={nodes.mesh_27_1.material} geometry={nodes.mesh_27_1.geometry} />
      </group>
      <group position={[-4466, 0, 994.34]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh material={nodes.mesh_28_0.material} geometry={nodes.mesh_28_0.geometry} />
        <mesh material={nodes.mesh_28_1.material} geometry={nodes.mesh_28_1.geometry} />
      </group>
      <group position={[-748.71, 0, 3377.81]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_29_0.material} geometry={nodes.mesh_29_0.geometry} />
        <mesh material={nodes.mesh_29_1.material} geometry={nodes.mesh_29_1.geometry} />
      </group>
      <group position={[2045.52, 0, 1936.7]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_30_0.material} geometry={nodes.mesh_30_0.geometry} />
        <mesh material={nodes.mesh_30_1.material} geometry={nodes.mesh_30_1.geometry} />
      </group>
      <group position={[-4698.35, 0, 2949.95]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_31_0.material} geometry={nodes.mesh_31_0.geometry} />
        <mesh material={nodes.mesh_31_1.material} geometry={nodes.mesh_31_1.geometry} />
      </group>
      <group position={[-2779.7, 0, 3474.62]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.77, 0.98, 0.4]}>
        <mesh material={nodes.mesh_32_0.material} geometry={nodes.mesh_32_0.geometry} />
        <mesh material={nodes.mesh_32_1.material} geometry={nodes.mesh_32_1.geometry} />
      </group>
      <group position={[-4884.27, 0, -475.71]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh material={nodes.mesh_33_0.material} geometry={nodes.mesh_33_0.geometry} />
        <mesh material={nodes.mesh_33_1.material} geometry={nodes.mesh_33_1.geometry} />
      </group>
      <group position={[-5922.07, 0, 1414.5]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh material={nodes.mesh_34_0.material} geometry={nodes.mesh_34_0.geometry} />
        <mesh material={nodes.mesh_34_1.material} geometry={nodes.mesh_34_1.geometry} />
      </group>
      <group position={[-5501.63, 0, 386.66]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.67, 0.67, 0.19]}>
        <mesh material={nodes.mesh_35_0.material} geometry={nodes.mesh_35_0.geometry} />
        <mesh material={nodes.mesh_35_1.material} geometry={nodes.mesh_35_1.geometry} />
      </group>
      <group position={[1702.71, 0, 2848.76]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_36_0.material} geometry={nodes.mesh_36_0.geometry} />
        <mesh material={nodes.mesh_36_1.material} geometry={nodes.mesh_36_1.geometry} />
      </group>
      <group position={[1415.26, 0, -929.69]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.77, 0.98, 0.4]}>
        <mesh material={nodes.mesh_37_0.material} geometry={nodes.mesh_37_0.geometry} />
        <mesh material={nodes.mesh_37_1.material} geometry={nodes.mesh_37_1.geometry} />
      </group>
      <group position={[-5.21, 0, -1479.88]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_38_0.material} geometry={nodes.mesh_38_0.geometry} />
        <mesh material={nodes.mesh_38_1.material} geometry={nodes.mesh_38_1.geometry} />
      </group>
      <group position={[-5150.66, 0, 2017.64]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.77, 0.98, 0.4]}>
        <mesh material={nodes.mesh_39_0.material} geometry={nodes.mesh_39_0.geometry} />
        <mesh material={nodes.mesh_39_1.material} geometry={nodes.mesh_39_1.geometry} />
      </group>
      <group position={[-4687.68, 0, 223.85]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.09, 0.98, 0.8]}>
        <mesh material={nodes.mesh_40_0.material} geometry={nodes.mesh_40_0.geometry} />
        <mesh material={nodes.mesh_40_1.material} geometry={nodes.mesh_40_1.geometry} />
      </group>
      <group position={[-6198.7, 0, 57.76]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_41_0.material} geometry={nodes.mesh_41_0.geometry} />
        <mesh material={nodes.mesh_41_1.material} geometry={nodes.mesh_41_1.geometry} />
      </group>
      <group position={[-5525.43, 0, -1098.36]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_42_0.material} geometry={nodes.mesh_42_0.geometry} />
        <mesh material={nodes.mesh_42_1.material} geometry={nodes.mesh_42_1.geometry} />
      </group>
      <group position={[-5201.32, 0, -1686.38]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.09, 0.98, 0.8]}>
        <mesh material={nodes.mesh_43_0.material} geometry={nodes.mesh_43_0.geometry} />
        <mesh material={nodes.mesh_43_1.material} geometry={nodes.mesh_43_1.geometry} />
      </group>
      <group position={[-4044.26, 0, -2005.66]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_44_0.material} geometry={nodes.mesh_44_0.geometry} />
        <mesh material={nodes.mesh_44_1.material} geometry={nodes.mesh_44_1.geometry} />
      </group>
      <group position={[-1144.23, 0, -2091.84]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh material={nodes.mesh_45_0.material} geometry={nodes.mesh_45_0.geometry} />
        <mesh material={nodes.mesh_45_1.material} geometry={nodes.mesh_45_1.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/ModelCity.gltf')
